name: "mod_senec"
description: "mod_senec HomeAssistant AddOn"
version: "0.2"
slug: "mod_senec"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
options:
  SENEC_HOST: 192.168.1.1
  debug_mode: false
schema:
  SENEC_HOST: str
  debug_mode: bool
